create table tb_category (id bigint not null auto_increment, created_at TIMESTAMP, name varchar(255), updated_at TIMESTAMP, primary key (id)) engine=InnoDB;
create table tb_product (id bigint not null auto_increment, date TIMESTAMP , description TEXT, img_url varchar(255), name varchar(255), price double precision, primary key (id)) engine=InnoDB;
create table tb_product_category (product_id bigint not null, category_id bigint not null, primary key (product_id, category_id)) engine=InnoDB;
create table tb_role (id bigint not null auto_increment, authority varchar(255), primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table tb_user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table tb_product_category add constraint FK5r4sbavb4nkd9xpl0f095qs2a foreign key (category_id) references tb_category (id);
alter table tb_product_category add constraint FKgbof0jclmaf8wn2alsoexxq3u foreign key (product_id) references tb_product (id);
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role (id);
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user (id);
